---

- name: Install snmp packages for Debian
  apt: name={{ item }} state=present
  become: true
  with_items:
    - snmp
    - snmpd
  notify: [ 'Restart snmpd' ]

- name: Configure snmpd.conf agentAddress
  template: dest=/etc/snmp/snmpd.conf src=snmpd.conf mode=600
  become: true
  notify: [ 'Restart snmpd' ]

